# -*- coding: utf-8 -*-
"""İmbd.app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OvB8bhKIXc9ktE_BFpif_NKGOaRydJ8J
"""

import gradio as gr
from keras.models import load_model
from keras.preprocessing.sequence import pad_sequences
from keras.datasets import imdb

# -----------------------
# Model ve kelime indeksi
# -----------------------
model = load_model("best_model.h5")
maxlen = 200
vocab_size = 10000
word_index = imdb.get_word_index()

# -----------------------
# Metni model için dönüştürme
# -----------------------
def text_to_sequence(text):
    tokens = text.lower().split()
    seq = [min(word_index.get(word, 2), vocab_size-1) for word in tokens]
    return pad_sequences([seq], maxlen=maxlen)

# -----------------------
# Tahmin fonksiyonu
# -----------------------
def predict_sentiment(review):
    try:
        seq = text_to_sequence(review)
        prob = float(model.predict(seq)[0][0])
        prediction = "Positive" if prob >= 0.5 else "Negative"
        prob_percent = int(prob*100)

        # Renk ve yüz ifadesi
        if prob >= 0.75:
            color = "#4caf50"
            emoji = "😃"
        elif prob >= 0.5:
            color = "#8bc34a"
            emoji = "🙂"
        elif prob >= 0.25:
            color = "#ff9800"
            emoji = "😐"
        else:
            color = "#f44336"
            emoji = "😞"

        html_output = f"""
        <div style='font-family:sans-serif; text-align:center; max-width:600px; margin:auto;'>
            <h2 style='color:{color};'>🎬 Tahmin: {prediction} {emoji}</h2>
            <p style='font-size:18px;'>💡 Olabilirlik: {prob:.2f}</p>
            <div style='background:#ddd; width:80%; margin: 10px auto; border-radius:5px;'>
                <div style='width:{prob_percent}%; background:{color}; padding:8px 0; border-radius:5px; color:white; font-weight:bold;'>{prob_percent}%</div>
            </div>
        </div>
        """
        return html_output
    except Exception as e:
        return f"⚠️ Hata oluştu: {str(e)}"

# -----------------------
# Gradio arayüzü
# -----------------------
iface = gr.Interface(
    fn=predict_sentiment,
    inputs=gr.Textbox(lines=5, placeholder="Film yorumunu buraya yazın..."),
    outputs=gr.HTML(),
    title="IMDb Sentiment Analyzer",
    description="Film yorumunu girin ve modelin duygu tahminini görsel olarak görün.",
    examples=[
        ["I absolutely loved this movie! The acting was fantastic and the story was gripping."],
        ["This was the worst movie I have ever seen. Totally boring and predictable."],
        ["The plot was confusing and the characters were not believable, but some scenes were beautiful."]
    ]
)

iface.launch(share=True)

